apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - appName: springboot-demo1
        cluster: https://kubernetes.default.svc
        namespace: springboot-demo1-dev
        path: apps/springboot-demo1/dev
      - appName: springboot-demo2
        cluster: "https://127.0.0.1:34621"
        namespace: springboot-demo2-dev
        path: apps/springboot-demo2/dev
  template:
    metadata:
      name: '{{appName}}-dev'
    spec:
      project: "default"
      # source:
      #   repoURL: https://github.com/myspotontheweb/argocd-workloads-demo.git
      #   targetRevision: HEAD
      #   path: '{{path}}'
      sourceHydrator:
        drySource:
          repoURL: https://bitbucket.gob.amadeus.net/scm/~paraj5/workload-demo.git
          targetRevision: HEAD
          path: '{{path}}'
          # Uncomment and fix the following lines if using templating logic
          # {{- if eq (index .path 1) "springboot-demo1" }}
          #helm:
            #valueFiles:
              #- values-change1.yaml
          # {{- end }}
        syncSource:
          #targetBranch: '{{path[1]}}-hydration'
          targetBranch: temp
          path: "{{path}}"

        #hydrateTo:
          #targetBranch: dev-hydration
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

