apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-matrix
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://bitbucket.gob.amadeus.net/scm/~paraj5/workload-demo.git
              revision: HEAD
              directories:
                - path: apps/*/dev
          - clusters: {}
  template:
    metadata:
      name: '{{clusters.name}}-{{path[1]}}-dev-{{path[2]}}'
    spec:
      project: "default"

      sourceHydrator:
        drySource:
          repoURL: https://bitbucket.gob.amadeus.net/scm/~paraj5/workload-demo.git
          targetRevision: HEAD
          path: '{{path}}'

          helm:
            valueFiles:
              - values-change1.yaml
        syncSource:

          targetBranch: temp
          path: "{{path}}"

        hydrateTo:
          targetBranch: dev-hydration

      destination:
        server: '{{clusters.server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

