apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://bitbucket.gob.amadeus.net/scm/~paraj5/workload-demo.git
      revision: HEAD
      directories:
      - path: apps/*/dev
  template:
    metadata:
      name: '{{path[1]}}-dev'
    spec:
      project: "default"
      # source:
      #   repoURL: https://github.com/myspotontheweb/argocd-workloads-demo.git
      #   targetRevision: HEAD
      #   path: '{{path}}'
      sourceHydrator:
        drySource:
          repoURL: https://bitbucket.gob.amadeus.net/scm/~paraj5/workload-demo.git
          targetRevision: HEAD
          path: '{{path}}'
        syncSource:
          targetBranch: '{{path[1]}}-hydration'
          #targetBranch: dev-hydration
          path: ""
        hydrateTo:
        	targetBranch: temp
            path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
